### PR TITLE
Add java wrapper libraries 

### PR DESCRIPTION
**Pull request by jollyjoker992**
This PR adds wrapper Java libraries for:
- [bc-crypto-base](https://github.com/BlockchainCommons/bc-crypto-base)
- [bc-shamir](https://github.com/BlockchainCommons/bc-shamir)
- [bc-sskr](https://github.com/BlockchainCommons/bc-sskr)

### CODE REVIEW

**Comment by peacekeeper** [comment]
I tried running `./gradlew clean test` in `bc-libs-java/crypto-base/java` this, but am getting these errors... I think I installed all the required dependencies. Any idea?

```
> Task :test
~/workspace-blockchain/bc-libs-java/deps/bc-crypto-base ~/workspace-blockchain/bc-libs-java/crypto-base/java
checking for gcc... clang-10
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang-10 accepts -g... yes
checking for clang-10 option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C preprocessor... clang-10 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for size_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for bzero... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating test/Makefile
config.status: creating config.h
config.status: config.h is unchanged
cd src && make clean
make[1]: Entering directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/src'
rm -rf libbc-crypto-base.a
rm -f memzero.o sha2.o hmac.o pbkdf2.o crc32.o
make[1]: Leaving directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/src'
cd test && make clean
make[1]: Entering directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/test'
rm -f test test.o test-utils.o
rm -rf *.dSYM
make[1]: Leaving directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/test'
cd test && make check
make[1]: Entering directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/test'
clang-10 -fPIC   -c -o test.o test.c
cd ../src && make libbc-crypto-base.a
make[2]: Entering directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/src'
clang-10 -fPIC   -c -o memzero.o memzero.c
clang-10 -fPIC   -c -o sha2.o sha2.c
clang-10 -fPIC   -c -o hmac.o hmac.c
clang-10 -fPIC   -c -o pbkdf2.o pbkdf2.c
clang-10 -fPIC   -c -o crc32.o crc32.c
ar rcs libbc-crypto-base.a memzero.o sha2.o hmac.o pbkdf2.o crc32.o
make[2]: Leaving directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/src'
clang-10 -fPIC   -c -o test-utils.o test-utils.c
clang-10   test.o ../src/libbc-crypto-base.a test-utils.o   -o test
./test
*** ALL TESTS PASSED ***UTING [2s]
make[1]: Leaving directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/test'
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
~/workspace-blockchain/bc-libs-java/crypto-base/java
Building libbc-crypto-base-jni.so...
../../base-jni/jni-utils.c:38:8: error: unknown type name 'uint8_t'
static uint8_t *to_uint8_t_array(JNIEnv *env, jbyteArray array) {
       ^
../../base-jni/jni-utils.c:41:5: error: use of undeclared identifier 'uint8_t'
    uint8_t *ret = calloc(count, sizeof(uint8_t));
    ^
../../base-jni/jni-utils.c:41:14: error: use of undeclared identifier 'ret'
    uint8_t *ret = calloc(count, sizeof(uint8_t));
             ^
../../base-jni/jni-utils.c:41:41: error: use of undeclared identifier 'uint8_t'
    uint8_t *ret = calloc(count, sizeof(uint8_t));
                                        ^
../../base-jni/jni-utils.c:42:12: error: use of undeclared identifier 'ret'
    memcpy(ret, elements, count);
           ^
../../base-jni/jni-utils.c:44:12: error: use of undeclared identifier 'ret'
    return ret;
           ^
../../base-jni/jni-utils.c:47:8: error: unknown type name 'uint8_t'
static uint8_t **to_uint8_t_2dimension_array(JNIEnv *env, jobjectArray array) {
       ^
../../base-jni/jni-utils.c:49:5: error: use of undeclared identifier 'uint8_t'
    uint8_t **ret = (uint8_t **) calloc(count, sizeof(uint8_t *));
    ^
../../base-jni/jni-utils.c:49:15: error: use of undeclared identifier 'ret'
    uint8_t **ret = (uint8_t **) calloc(count, sizeof(uint8_t *));
              ^
../../base-jni/jni-utils.c:49:32: error: expected expression
    uint8_t **ret = (uint8_t **) calloc(count, sizeof(uint8_t *));
                               ^
../../base-jni/jni-utils.c:49:22: error: use of undeclared identifier 'uint8_t'
    uint8_t **ret = (uint8_t **) calloc(count, sizeof(uint8_t *));
                     ^
../../base-jni/jni-utils.c:52:9: error: use of undeclared identifier 'ret'
        ret[i] = to_uint8_t_array(env, obj);
        ^
../../base-jni/jni-utils.c:54:12: error: use of undeclared identifier 'ret'
    return ret;
           ^
../../base-jni/jni-utils.c:57:67: error: unknown type name 'uint8_t'
static void copy_to_jbyteArray(JNIEnv *env, jbyteArray dst, const uint8_t *src, size_t src_len) {
                                                                  ^
14 errors generated.

> Task :test FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/markus/workspace-blockchain/bc-libs-java/crypto-base/java/build.gradle' line: 22

* What went wrong:
Execution failed for task ':test'.
> Process 'command 'scripts/build.sh'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
4 actionable tasks: 4 executed
```

**Comment by jollyjoker992** [comment]
@peacekeeper Thanks for testing. That was my mistake, i already fixed it. You can pull the latest code and try again.

**Comment by peacekeeper** [comment]
@jollyjoker992 thanks, just tried it. Now building the native code seems to work, but I'm getting an error in the Java tests:

```
make[2]: Leaving directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/src'
clang-10 -fPIC   -c -o test-utils.o test-utils.c
clang-10   test.o ../src/libbc-crypto-base.a test-utils.o   -o test
./test
*** ALL TESTS PASSED ***
make[1]: Leaving directory '/home/markus/workspace-blockchain/bc-libs-java/deps/bc-crypto-base/test'
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
~/workspace-blockchain/bc-libs-java/crypto-base/java
Building libbc-crypto-base-jni.so...
Done. Checkout the release file at build/release/libbc-crypto-base-jni.so

com.bc.cryptobase.CryptoBaseTest > testCRC32 FAILED
    org.junit.ComparisonFailure at CryptoBaseTest.java:58

4 tests completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.
```

**Comment by jollyjoker992** [comment]
@peacekeeper There was a JDK bug report [here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8215928). I will keep investigating the problem and get back to you soon. Thanks!

**Comment by jollyjoker992** [comment]
@peacekeeper I decide to use [Adopt Open JDK](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases) for fixing the unexpected JVM crash that caused your issue on Linux. Please checkout the new code and try again. 
Notice that i also updated the installation instruction a bit so just want make sure you're aware about that. 
Thanks!

**Comment by jollyjoker992** [comment]
@peacekeeper Another thing that since you already installed the `openjdk8` before so it would keep using old jdk version even you run `scripts/install_dep.sh` to migrate to `AdoptOpenJDK`. 
You can check it by running `java -version`. If the result is 
```console
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```
you are using AdoptOpenJDK and then can run the test normally.
If not, you have to remove the old version of `openjdk8` and then check again until it shows as above.

**Comment by peacekeeper** [comment]
@jollyjoker992 thanks, I'm sorry but installing AdoptOpenJDK seems very complicated (I've never heard of this before), so I decided not to do that.

Instead, I now tried it with the standard `openjdk-11-jdk` from Debian, and I was able to run `./scripts/build.sh` and `./gradlew assemble`. However `./gradlew test` still gives the same "testCRC32 FAILED" error as above.

I then copied `./build/release/libbc-crypto-base-jni.so` into my `/usr/lib`, and I used `bc-crypto-base-java-1.0.0.jar` to successfully run the following code:

```
import org.apache.commons.codec.binary.Hex;
import com.bc.cryptobase.CryptoBase;

public class Test {

	public static void main(String[] args) throws Exception {

		System.out.println(Hex.encodeHexString(CryptoBase.sha256("HelloWorld".getBytes())));
	}
}
```

So I guess it sort of works! But I would really recommend to somehow make this work with standard JDKs...

**Comment by jollyjoker992** [comment]
@peacekeeper AdoptOpenJdk is just based on openJDK and it's been used widely as far as i know. As i mentioned before, that's a reported bug of openJDK8 (seems like it's been fixed in later versions, i'm not sure) so it caused the CRC32 tests failed (jvm is crashed) and the rest works normally. I dont know how it comes and how AdoptOpenJDK can fix it. I will keep investigate something and get back to you. Thanks!

**Review by peacekeeper — APPROVED** [review]
From my perspective this seems to be working now (minus the JDK bug that would be nice to somehow get rid of). Thanks @jollyjoker992.. !

**Pull request merged**
